### ISSUE TITLE
Empty contact ID list on ubuntu with Gajim or Telepathy

### ISSUE THREAD

**Issue by tigre-bleu** [titilambert/harbour-squilla#1]
My phone is on Wifi and my PC on ethernet but all on the same network.

Neither Gajim nor Empathy/Telepathy see the Jolla phone and in the other way the contact ID list is empty on the Jolla phone.

In the readme you ask to hit refresh in that case, but there is no refresh button.

Installed version is the one from openrepos (0.1-1)

**Comment by titilambert** [comment]
Hello !
The wifi does not work for now ... The Jolla device filter all multicast packets... I'm trying to get a workaround ...

**Comment by tigre-bleu** [comment]
Mmm... ok I take note but I'm confused, how is this supposed to work at the moment? via usb?

Because you state that the work on usb is started but not finished.

**Comment by titilambert** [comment]
I push the version 0.2 just now. Could you tell me if you still have this issue ?
Thanks !

**Comment by tigre-bleu** [comment]
Yeah it looks like it's working. 

I had troubles figuring it out because Gajim must be started _after_ squilla for the list to be filled.

**Comment by titilambert** [comment]
Thanks for you feed back !
Do you use it by wifi or usb ?
Did you try with pidgin ?

**Comment by tigre-bleu** [comment]
No I don't use pidgin, just Gajim and Empathy but for some reason the telepathy plugin seems not to work.

The phone is connected to Wifi.

**Comment by titilambert** [comment]
Oki  !
Compatibility bug between telepathy and squilla ! (I suspect a xml/xmpp problem :) )
I close this bug and I open a new one

**Comment by titilambert** [comment]
See here #4
